config/routes.rb
WebLoggerGem::Application.routes.draw do
  resources :web_loggers
  root 'web_loggers#index'

end

app/models/web_logger.rb
require 'singleton'

class WebLogger
  include Singleton
  attr_reader :files
  attr_accessor :n
  N_VALUE = 100

  def initialize
    begin
      @n = N_VALUE
      @files = Dir.entries(Rails.root.join('log').to_s).select { |file| file.include? '.log' }
    rescue
      return []
    end
  end

  def n=(value)
    if value.present? && value.to_i > 0
      @n =value.to_i
    else
      @n = N_VALUE
    end

  end

  # @return [log entries array]
  # @param [File name] file_name
  # @param [strings to return] n
  def tail(file_name)
    begin
      @files.include?(file_name) ? `tail -n #{@n} log/#{file_name}`.lines : []
    rescue
      return []
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web_loggers_controller.rb
class WebLoggersController < ApplicationController

  def index
    @web_logger ||= WebLogger.instance
    @web_logger.n = params[:n]
    params[:n] = @web_logger.n
    log_file_name = params[:file_name] || "#{Rails.env}.log"
    @files = @web_logger.tail(log_file_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_loggers_helper.rb
module WebLoggersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebLoggerGem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_loggers/index.html.erb
<style>
    .links {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 14px;
    }

    .links a {
        color: rgb(0, 136, 204);
    }

    .links a:visited {
        color: rgb(0, 85, 128);
    }

    .log_table {
        width: 100%;
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-size: 14px;
    }

    .log_table td, th {
        border-bottom: 1px dashed lightgray;
        padding: 5px;
    }

    td.error {
        color: #ac0000;
    }


</style>

<div class="links">
  <% @web_logger.files.each do |file| %>
      <%= link_to file, web_loggers_path(file_name: file, n: params[:n]) %>
  <% end %>
</div>


<div>
  <table class="log_table">
    <thead>
    <th></th>
    </thead>
    <tbody>
    <% @files.each do |line| %>
        <tr>
          <td <%= 'class=error' if line.downcase.include?('error') %>>
            <%= line %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<p></p>
<div class="links">
  <%= link_to 'Less..', web_loggers_path(file_name: params[:file_name], n: (params[:n].to_i/1.5).to_i) %>
  <% @web_logger.files.each do |file| %>
      <%= link_to file, web_loggers_path(file_name: file, n: params[:n]) %>
  <% end %>
  <%= link_to 'More..', web_loggers_path(file_name: params[:file_name], n: (1.5 * params[:n].to_i).to_i) %>
</div>

<script type="text/javascript" charset="utf-8">
    window.scrollTo(0, document.body.scrollHeight);
</script>